### ISSUE TITLE
Minor typos in several chapters

### ISSUE THREAD

**Issue by agailloty** [koalaverse/homlr#13] opened 2019-07-02 09:33 UTC
Hi thanks for this book. While reading I come accross many minor typos in the text. I'll try to reference them here.

The typos and my propositions will be in **bold**; redundant words are <s>strikeouted</s>

In Chapter 4.8 :  The last paragraph of the section :

> gradually decreases for **lessor** important variables.
Correct would be : 
> gradually decreases for **lesser** important variables.

In Chapter 6.2 : the paragraph right after the note to the reader.

> Many real-life data sets, like those **cmmon** to text mining
Correct would be : 
> Many real-life data sets, like those **common** to text mining

In Chapter 9.5 . The last sentence of the second paragraph

> "Basically, this is telling us that Overall_Qual is an important predictor **os** sales price"
Correct would be :
>Basically, this is telling us that Overall_Qual is an important predictor **of** sales price.

In Chapter 10.2. The last sentence of the "note to the reader"

> you’ll often find that the averaged guesses tends to be a lot closer to the true **numnber**.
Correct would be 
> you’ll often find that the averaged guesses tends to be a lot closer to the true **number**

In 10.3. The fourth (4th) line of the first paragraph

> we’re keeping bias low and **avriance ** high
Correct would be:
> we’re keeping bias low and **variance** high

In 10.4 last sentence of the third paragraph

> how the OOB error closely <s>closely</s> approximates the test error.

In Chapter 11, second line
> collection of de-correlated trees to <s>to</s> further improve

In 11.4.3, the fifth line

> if computation time is a concern **than** you can
Correct would be:
> if computation time is a concern **then** you can  

In 11.7, second line

> (**witht he** exception of surrogate splits)
Correct would be : 
> (**with the** exception of surrogate splits)

I'm still reading the book, so I will keep posting the issues.

**Comment by bgreenwell** [comment] 2019-07-02 10:15
Thanks @agailloty, much appreciated!

**Comment by raycblai** [comment] 2019-09-08 08:08
Chapter 3.2

“best transofrmation to an approximate normal distribution” - typo

**Comment by bradleyboehmke** [comment] 2019-09-13 13:11
These are good catches @agailloty . We have corrected these in the PDF version. Note that the online version will not be updated until we finalize the PDF.

**Comment by erickeniuk** [comment] 2019-09-18 20:11
I believe this is right on the 2nd or 3rd page under the unsupervised learning introduction. - “DespiDe” rather than “Despite”

 “Despide its subjectivity, the importance of unsupervised learning should not be overlooked and such techniques are often used in organizations to:”

**Comment by william3031** [comment] 2019-09-26 06:14
Chapter 3.3:

informative missingess (Kuhn and Johnson 2013)   - missing the second 'n'.

**Comment by bradleyboehmke** [comment] 2019-09-29 17:53
All entries to this point have been updated.

**Comment by mmelcher76** [comment] 2019-09-30 10:18
I also want to thank you for this excellent book. Some typos I found (in the first 3 chapters):

* chapter 2.2.1, the Note: "we'11" instead of "we'll"
* chapter 2.6, 4th sentence, in brackets: "outpuf" instead of "output"  
* chapter 2.6.1, MSE formula: there is a slight inconsistency in the MSE formula: capital Y, in all others there is a y.
* chapter 3.2, 1st sentence, in brackets: "where (we?) require ..."
* chapter 3.3, 2nd paragraph, 2nd sentence: "definciencies" 
* caption on figure 3.3: "issing instead of missing
* chapter 3.3.1, shortly before vis_miss(): "inidcated"
* chapter 3.3.1, 2nd last sentence, in brackets: "enetered"
* chapter 3.3.2, 2nd sentence: "yo"
* chapter 3.3.2.2, end of 2nd paragraph: "burdomesome"
* chapter 3.4, 3rd paragraph: "uniquen"
* chapter 3.4, in the itemization: there seems to be a markdown/latex error (dollar sign!) twice!
* chapter 3.4, paragraph after itemization: "adventageous"
* chapter 3.4 [not really an error]: in the nearZeroVar() call, a space before the "=" in the saveMetric argument would be better     

MM

**Comment by j-ryanhart** [comment] 2019-10-08 17:12
This is a great read, things are explained very well.  Through ch. 7, here are some things I notice:

2.6.1 line 3 of 'Deviance'
...'compares' rather than 'computes' a saturated model to an unsaturated model...

2.7 multiple lines
(#2) Grid Search:  we specify the hyperparameter values to assess (k = 2, 4, 6, ..., 25).  These values do not match those in the hyper_grid call:  hyper_grid <- expand.grid(k = seq(2, 25, by = 1))... suggest 'values to assess (k = 2, 3, 4, ..., 25)'

4.8 line 27
...'LS coefficient' suggest...'of the OLS coefficient' for consistency

6.3 
...'Apply ridge regression to attrition data' ... should this be 'Ames_housing' data?

6.4 
...'as we constrain it further (i.e., continue to increase the penalty), our MSE starts to decrease' ... should this be 'MSE starts to increase'?

7.2 
... 'where C_1(x) represents X values ranging from c_1 <= X < c_2, C_2(X) represents X values'... you begin with lowercase x representing the C_1 portion of X,
but with C2, you represent this range of X also with X.  Should this be C_2(x), and then later on line 20, C_d(x) also?

7.2.1 
... 'to capture the nonlinearity relationships'... should this be 'nonlinear'?

**Comment by bradleyboehmke** [comment] 2020-02-01 17:07
Thanks everyone for these edits. These have all been addressed and updated on the online version of the book. I'm closing this out and new typos/corrections can come in as new issues. Thanks!

**Closed by bradleyboehmke** 2020-02-01 17:07 UTC
Labels: 01 Introduction to ML, 02 Modeling Process, 03 Feature & Target Eng, 04 Linear Regression, 06 Regularized Regression, 07 MARS, 09 Decision Trees, 10 Bagging, 11 Random Forests, typo
